# Generated by Django 3.0.3 on 2020-03-28 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breed',
            old_name='name',
            new_name='breed_name',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='breed',
            new_name='breed_name',
        ),
    ]
